'use strict';
const $=s=>document.querySelector(s);let rows=[],selected='',authenticated=false,setup=false,pc=null,mic=null,voiceID='',callRows=[],installPrompt=null,loading=false,sendID='';
const text=(el,s)=>{el.textContent=s};const format=t=>new Date(t).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false});
async function api(path,options={}){const r=await fetch(path,{credentials:'same-origin',...options,headers:{'Content-Type':'application/json',...options.headers}});const b=await r.json();if(!r.ok){if(r.status===401&&path!=='/api/auth'){authenticated=false;$('#app').hidden=true;$('#auth').hidden=false;stopLocalAudio()}throw Error(b.error||'请求失败')}return b}
const post=(path,data)=>api(path,{method:'POST',body:JSON.stringify(data)});
function toast(s){text($('#toast'),s);$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,5000)}
async function init(){try{const state=await api('/api/auth');setup=state.setup_required;$('#setup-label').hidden=!setup;$('#setup-help').hidden=!setup;text($('#login-button'),setup?'创建自己的账户':'登录');$('#password').autocomplete=setup?'new-password':'current-password';if(state.authenticated)loggedIn()}catch(e){text($('#auth-error'),'服务暂时无法连接，请刷新重试。')}}
function loggedIn(){authenticated=true;$('#auth').hidden=true;$('#app').hidden=false;refresh();if('serviceWorker'in navigator&&isSecureContext)navigator.serviceWorker.register('/sw.js').catch(()=>{});}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();$('#login-button').disabled=true;try{await post('/api/auth',{username:$('#username').value,password:$('#password').value,setup_token:$('#setup-token').value.trim()});$('#password').value='';$('#setup-token').value='';loggedIn()}catch(e){text($('#auth-error'),e.message)}finally{$('#login-button').disabled=false}});
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{const tab=b.dataset.tab;document.querySelectorAll('.panel').forEach(el=>el.hidden=el.id!==tab);document.querySelectorAll('[data-tab]').forEach(el=>el.classList.toggle('active',el.dataset.tab===tab));text($('#page-title'),{inbox:'你的短信',phone:'拨一通电话',settings:'我的设备'}[tab]);if(tab==='phone')refreshCalls()}));
async function refresh(){if(!authenticated||loading)return;loading=true;try{const [status,messages]=await Promise.all([api('/api/status'),api('/api/messages')]);rows=messages;renderList();renderDetail();text($('#operator'),status.operator||'SIM 线路');text($('#network'),status.connected?(status.network_mode||'蜂窝网络')+' · '+(status.reg_status_text||'等待注册'):'等待模块连接');text($('#signal'),status.signal_dbm&&status.signal_dbm>-150?status.signal_dbm+' dBm':'—');text($('#connection'),status.sim_inserted?'SIM 已识别':'等待 SIM');text($('#firmware'),status.firmware||'—');text($('#audio-device'),status.audio_device||'—');text($('#secure-state'),status.https?'HTTPS 安全连接':'局域网 HTTP');$('#warning').hidden=!status.error;text($('#warning'),status.error||'');if(!isSecureContext)text($('#install-help'),'当前通过局域网 HTTP 访问。配置 HTTPS 后，即可完整安装到主屏幕并使用麦克风通话。短信网页现在可以使用。');}catch(e){toast(e.message)}finally{loading=false}}
function renderList(){const query=$('#search').value.toLowerCase();const peers=new Map();for(const m of rows){if(!query||m.peer.toLowerCase().includes(query)||m.content.toLowerCase().includes(query)){if(!peers.has(m.peer))peers.set(m.peer,m)}}text($('#count'),rows.filter(m=>m.direction==='incoming').length);$('#messages').replaceChildren();if(!peers.size){const el=document.createElement('div');el.className='empty';const h=document.createElement('h3');text(h,query?'没有找到相关短信':'还没有短信');const p=document.createElement('p');text(p,query?'换一个号码或关键词试试。':'发送到这张 SIM 的短信会显示在这里。');el.append(h,p);$('#messages').append(el);return;}for(const [peer,m]of peers){const b=document.createElement('button');b.className='message-row'+(selected===peer?' selected':'');const avatar=document.createElement('span');avatar.className='avatar';text(avatar,peer.slice(-2));const body=document.createElement('div');body.className='row-body';const top=document.createElement('div');top.className='row-top';const name=document.createElement('strong');text(name,peer);const t=document.createElement('time');text(t,format(m.timestamp));top.append(name,t);const p=document.createElement('div');p.className='preview';text(p,(m.direction==='outgoing'?'你：':'')+m.content);body.append(top,p);b.append(avatar,body);b.addEventListener('click',()=>{selected=peer;renderList();renderDetail();if(innerWidth<700)$('#detail').scrollIntoView({behavior:'auto',block:'nearest'})});$('#messages').append(b)}}
function renderDetail(){if(!selected)return;const detail=$('#detail');detail.replaceChildren();const head=document.createElement('div');head.className='detail-head';const title=document.createElement('div');const h=document.createElement('h3');text(h,selected);const s=document.createElement('small');text(s,'与这条线路的短信');title.append(h,s);head.append(title);detail.append(head);const conversation=rows.filter(m=>m.peer===selected).slice(0,100).reverse();for(const m of conversation){const bubble=document.createElement('div');bubble.className='bubble'+(m.direction==='outgoing'?' outgoing':'');const p=document.createElement('span');text(p,m.content);const t=document.createElement('time');text(t,format(m.timestamp)+(m.direction==='outgoing'?' · '+({submitted:'已提交运营商',pending:'提交中',unknown:'结果未知，请勿重复发送'}[m.status]||m.status):''));bubble.append(p,t);if(m.code){const copy=document.createElement('button');copy.className='quiet compact';text(copy,'复制验证码 '+m.code);copy.addEventListener('click',()=>copyText(m.code));bubble.append(copy)}detail.append(bubble)}const actions=document.createElement('div');actions.className='detail-actions';const reply=document.createElement('button');reply.className='primary';text(reply,'回复短信');reply.addEventListener('click',()=>compose(selected));actions.append(reply);detail.append(actions)}
async function copyText(s){try{await navigator.clipboard.writeText(s);toast('验证码已复制')}catch{toast('当前浏览器无法复制，请长按短信内容复制')}}
$('#search').addEventListener('input',renderList);$('#refresh').addEventListener('click',async()=>{try{await post('/api/messages/refresh',{});toast('正在同步短信');setTimeout(refresh,1500)}catch(e){toast(e.message)}});
function compose(peer=''){sendID=crypto.randomUUID?crypto.randomUUID():Date.now().toString(16)+Math.random().toString(16).slice(2);$('#recipient').value=peer;$('#sms-content').value='';text($('#send-error'),'');$('#compose').showModal()}
$('#compose-open').addEventListener('click',()=>compose());$('#compose-close').addEventListener('click',()=>$('#compose').close());
$('#send-form').addEventListener('submit',async e=>{e.preventDefault();$('#send-button').disabled=true;try{const m=await post('/api/messages/send',{phone:$('#recipient').value.trim(),message:$('#sms-content').value,request_id:sendID});if(m.status!=='submitted')throw Error('发送结果尚未确认，请先核对记录，不要重复发送');selected=m.peer;$('#compose').close();toast('短信已提交运营商');await refresh()}catch(e){text($('#send-error'),e.message);await refresh()}finally{$('#send-button').disabled=false}});
for(const k of '123456789*0#'){const b=document.createElement('button');text(b,k);b.addEventListener('click',async()=>{if(callRows.length===1&&callRows[0].state===0){try{await action('dtmf',{digit:k})}catch(e){toast(e.message)}}else{$('#dial-number').value+=k}});$('#keypad').append(b)}
function stopLocalAudio(){if(pc){pc.onconnectionstatechange=null;pc.close();pc=null}if(mic){mic.getTracks().forEach(t=>t.stop());mic=null}voiceID='';$('#disconnect-audio').hidden=true;text($('#audio-state'),'音频未连接')}
async function connectAudio(){if(!isSecureContext)throw Error('麦克风通话需要通过 HTTPS 打开家信');if(pc&&pc.connectionState==='connected')return;if(pc)stopLocalAudio();mic=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true},video:false});pc=new RTCPeerConnection({iceServers:[]});const audio=new Audio();audio.autoplay=true;pc.ontrack=e=>{audio.srcObject=e.streams[0]||new MediaStream([e.track]);audio.play().catch(()=>toast('请点一下页面启用声音'))};const sender=pc.addTrack(mic.getAudioTracks()[0],mic);const transceiver=pc.getTransceivers().find(t=>t.sender===sender);const codecs=RTCRtpSender.getCapabilities('audio').codecs.filter(c=>c.mimeType.toLowerCase()==='audio/pcmu');if(!codecs.length)throw Error('浏览器不支持此模块的语音格式');if(transceiver.setCodecPreferences)transceiver.setCodecPreferences(codecs);pc.onconnectionstatechange=()=>{const state=pc?.connectionState;text($('#audio-state'),state==='connected'?'麦克风已连接，可以拨打或接听。':'正在连接音频…');if(state==='failed'||state==='disconnected'){stopLocalAudio();api('/api/voice',{method:'DELETE'}).catch(()=>{});toast('音频连接已断开，请重新连接')}};const offer=await pc.createOffer();await pc.setLocalDescription(offer);await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('语音候选地址收集超时')),12000);if(pc.iceGatheringState==='complete'){clearTimeout(timer);resolve();return}pc.onicegatheringstatechange=()=>{if(pc?.iceGatheringState==='complete'){clearTimeout(timer);resolve()}}});const answer=await post('/api/voice/offer',pc.localDescription);voiceID=answer.voice_id;await pc.setRemoteDescription({type:answer.type,sdp:answer.sdp});$('#disconnect-audio').hidden=false}
$('#connect-audio').addEventListener('click',async()=>{try{await connectAudio()}catch(e){stopLocalAudio();toast(e.message)}});$('#disconnect-audio').addEventListener('click',async()=>{try{await api('/api/voice',{method:'DELETE'});stopLocalAudio()}catch(e){stopLocalAudio();toast(e.message)}});
async function action(action,extra={}){return post('/api/calls/action',{action,voice_id:voiceID,call_id:callRows[0]?.id||'',...extra})}
$('#dial').addEventListener('click',async()=>{const b=$('#dial');b.disabled=true;try{await action('dial',{number:$('#dial-number').value.trim()});toast('正在拨号');await refreshCalls()}catch(e){toast(e.message)}finally{b.disabled=false}});
for(const name of ['answer','reject','hangup'])$('#'+name).addEventListener('click',async()=>{try{await action(name);await refreshCalls()}catch(e){toast(e.message)}});
async function refreshCalls(){if(!authenticated||$('#phone').hidden)return;try{callRows=await api('/api/calls');const c=callRows[0];text($('#call-number'),c?(c.number||'未知号码'):'线路空闲');text($('#call-state'),c?({0:'通话中',1:'通话保持',2:'正在拨号',3:'等待对方接听',4:'有来电',5:'有等待接听的来电'}[c.state]||'状态未知'):'电话音频需要 HTTPS，以及浏览器麦克风权限。');const ring=c&&(c.state===4||c.state===5);$('#answer').hidden=!ring;$('#reject').hidden=!ring;$('#hangup').hidden=!c||ring;}catch(e){text($('#call-state'),e.message)}}
$('#logout').addEventListener('click',async()=>{try{if(pc)await api('/api/voice',{method:'DELETE'});stopLocalAudio();await api('/api/auth',{method:'DELETE'});location.reload()}catch(e){toast(e.message)}});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#install').hidden=false});$('#install').addEventListener('click',async()=>{if(installPrompt){await installPrompt.prompt();installPrompt=null;$('#install').hidden=true}});
document.addEventListener('visibilitychange',()=>{if(!document.hidden){refresh();refreshCalls()}});setInterval(()=>{if(!document.hidden)refresh()},12000);setInterval(()=>{if(!document.hidden)refreshCalls()},3000);init();
